name: gg
channels:
  - pytorch
  - plotly
  - defaults
dependencies:
  - pillow
  - pip
  - python=3.8
  - cudatoolkit=10.2
  - scipy
#  - pytorch-cuda>=1.10.1
#  - torchvision
  - pip:
    - moviepy
    - numpy
    - opencv-python
    - pandas
    - plotly
    - tensorboard>=1.15
    - tqdm
    - wget
    - lmdb
    - ray
    - ninja
    - scikit-learn
    - termcolor
    - imageio==2.4.1
    - torch==1.10.1
    - torchvision==0.11.2
    - ipython
